# Generated by Django 4.0.3 on 2022-04-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('hid', models.IntegerField(primary_key=True, serialize=False)),
                ('h_date', models.DateField()),
                ('diagnosis', models.CharField(max_length=150)),
                ('prid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('blood', models.CharField(max_length=8)),
                ('place', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=150)),
                ('qty', models.CharField(max_length=20)),
                ('routine', models.CharField(max_length=8)),
                ('duration', models.CharField(max_length=20)),
                ('scan_image', models.ImageField(upload_to='')),
                ('href', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docrapp.history')),
                ('ppref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docrapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='pref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docrapp.patient'),
        ),
    ]
