# Generated by Django 3.1.6 on 2022-04-11 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docrapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='prid',
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
